IBM/ibm.github.io

orgs.js
Hello, 
I've added the https://github.com/beloglazov/couchdb-scala repository to the list. Is it sufficient to just update the `orgs.js` file?
Thanks,
Anton
=> Added the beloglazov/couchdb-scala repository

orgs.js
I added the TransProg repository.
=> added TransProg

orgs.js
IBM-Bluemix, watson-developer-cloud, IBM-Watson, ibm-research
=> Added 4 orgs to the list

index.html
=> Revert "Fixforks"

orgs.js
=> Adding organization Digital Experience

orgs.js
Hi,
This is a PR to link my open sourced project "cargo" to ibm.github.io.
AWSOM Proposal Ref #: RES022520151123
COO Ref#: IN720150034
github link for project: https://github.com/nadgowdas/cargo
=> PR for cargo project

orgs.js
trying to list my epanetReader project on the IBM portal
=> added bradleyjeck/epanetReader to orgs.js

orgs.js
AWSOM Proposal number: ANA027620150908
If I've done this wrong, sorry - please ping me.
=> Add git-history-data to orgs list

orgs.js
=> add strongloop

orgs.js
=> add cicsdev

css/style.css, index.html
* makes it easier to tweak UI by changing .css
* replaced `Foo <br> <span> Bar </span> »`  with `Foo <b>Bar</b>`
to declutter the source html
=> Move style= to .css in the jumbotron

css/style.css, index.html
* Added a percent indicator. (Fades out once at 100%)
* Use international numbers where available.
* Strange scope errors - the onclick analytics would only fire after
a search happened. Probably not what was desired.
* Moved the search and onclick handlers into the main jquery function
=> Add progress label. Fix JS errs.

css/style.css, index.html
Reverts IBM/ibm.github.io#44
@srl295 merging this basically brought the page load to a crawl, or locked up the page completely about half way
=> Revert "Add progress label. Fix JS errs."

index.html
bump © from 2014 to 2016. Also, update it dynamically as a fallback.
=> Ensure © is up to date

css/style.css
(Sorry no screenshots for cards/searchbox)
Before:
After:
=> Fix word overflow on main buttons, cards and search box for small devices /w before/after shots

orgs.js
AWSOM proposal #CLG206220170205
closes csync/TogetherStream#472
=> Added Together Stream to the list

orgs.js
Update the list of organizations to include the work being done by the z/OS Connect EE team.
=> Add z/OS Connect EE organization

index.html
IBM favicon added to IBM @ Github.
=> Favicon added to page

css/style.css
I changed the border color and border radius of search input box. It's look great.
=> Search box input UI improvement

orgs.js
Added ibm-watson-iot org for our open source projects to be aggregated and displayed under IBM.io site.
=> Added ibm-watson-iot org

css/style.css
Currently search box is right aligned. I aligned search box to Center. It is look great in center and more user friendly. We can give it a try.
=> Center aligned search box.

orgs.js
=> Adds IzODA organization

css/style.css
- Searchbar should looking nice on all resolutions (up to 1080p, could not test to 4k)
- I noticed that this CSS does contain different coding styles, fixed that (changed to the most used style)
- I also noticed that many spaces are wrong placed, fixed that
=> Fix search bar / Fix spaces & coding style

.travis.yml, package.json
add some basic lint tests to orgs.js since that's what everyone modifies
=> add jshint

css/style.css, index.html
- Changed commit #44 which only includes progress (and changed style slightly)
- On startup (nearly everytime on F5) showed previously just "0" which changes to "X %" on load. Now it shows "0 %" at the start
- Fixed some format (theres a lot more to fix) to make them easier to find / edit
- Also checked mobile-view and it does fit well
- This change does not decrease performance  (or its not noticeable)
- Added fix for description "null" if no description is given on a repository (closes #96)
=> Added repository-progress-view on startup and fixes description issues

index.html
- Changed dirty fix to a more nicely one
- Edited copyright slightly. It should display always current year
=> Clean up fix from #97

css/style.css, index.html
- According to comment from @srl295 at #99 it shouldn't be 'less'. View more on https://en.wikipedia.org/wiki/Fewer_vs._less
- Also fixed some format in css
- Changed visibility of font. Its now more clear to read.
> ![without_change](https://user-images.githubusercontent.com/10914774/32404507-dbf5ee4e-c150-11e7-9baf-bced356beca4.PNG)
>  ![with_change](https://user-images.githubusercontent.com/10914774/32404505-d16826a4-c150-11e7-8589-783d03899ad4.PNG)
=> Changed 'less' to 'fewer' 

orgs.js
Hi,
Please add www.qiskit.org :)
/luciano
=> add QISKit

orgs.js
Status: 301 Moved Permanently:
andrewlow/node  -->  ibmruntimes/node
andrewlow/v8ppc  -->  ibmruntimes/v8ppc
andrewlow/v8z  -->  ibmruntimes/v8z
apache/incubator-systemml  -->  apache/systemml
=> Update permanently moved repositories

css/style.css, index.html
=> Fix search bar

css/style.css
=> Fix search bar for mobile

orgs.js
...to keep parser(s) happy ;-)
=> Remove trailing comma in "ibm-s390-tools" entry

orgs.js
```JSON
...
{
"name": "ComputationalGenomics",
"type": "org"
},
{
"name": "ibm-watson-iot",
"type": "org"
},
{
"name": "IzODA",
"type": "org"
},
{
"name": "ComputationalGenomics",
"type": "org"
},
...
```
=> Remove duplicate org "ComputationalGenomics"

orgs.js
SparkTC moved to https://github.com/codait/
=> The "SparkTC" org is now "CODAIT"

orgs.js
=> add api4json

orgs.js
snowpatch is a continuous integration tool maintained as an IBM open source
project.
Signed-off-by: Andrew Donnellan <andrew.donnellan@au1.ibm.com>
=> orgs.js: Add ruscur/snowpatch

orgs.js
SIgned-off-by: Christopher Ferris <chrisfer@us.ibm.com>
=> add IBM org

orgs.js
Signed-off-by: Christopher Ferris <chrisfer@us.ibm.com>
=> fix IBM org

orgs.js
For IBM MQ and related messaging repositories
=> Add ibm-messaging org
